import {test,afterAll,expect} from 'vitest';
import pg from 'pg';
import {randomUUID} from 'node:crypto';
process.env.NODE_ENV='test';
const schema='triage_test_'+randomUUID().replaceAll('-','');
if(!process.env.DATABASE_URL)throw Error('Dedicated test database required');
const admin=new pg.Client({connectionString:process.env.DATABASE_URL});await admin.connect();await admin.query('CREATE SCHEMA '+schema);process.env.PGOPTIONS='-c search_path='+schema;
const {pool}=await import('../apps/history-api/src/db.js');
const {migrateVersioned}=await import('../apps/history-api/src/migrations.js');await migrateVersioned();
const {Directory}=await import('../apps/history-api/src/directory.js');
const {bindMail}=await import('../apps/history-api/src/common-mail.js');
const team=randomUUID();await pool.query('INSERT INTO team VALUES($1,$2)',[team,'Synthetic']);
const directory=new Directory(team);
const a=await directory.login({issuer:'https://test/',subject:'a',email:'a@example.test'}),b=await directory.login({issuer:'https://test/',subject:'b',email:'b@example.test'});
const sa=await directory.registerSource(a,{instanceId:randomUUID(),displayName:'A'}),sb=await directory.registerSource(b,{instanceId:randomUUID(),displayName:'B'});
const evidence={messageId:'<shared@example.test>',subject:'Synthetic shared mail',from:[{address:'sender@example.test'}],sentAt:'2026-09-28T00:00:00Z'};
const proof=(mailId:number)=>({mailId,evidence,verifiedAt:new Date().toISOString()});
afterAll(async()=>{await pool.end();await admin.query('DROP SCHEMA '+schema+' CASCADE');await admin.end();});
test('cross-source identity is team-scoped, idempotent, and grants no source access',async()=>{
 const [x,y]=await Promise.all([bindMail(a,sa.id,proof(123)),bindMail(b,sb.id,proof(789))]);
 expect(x.commonId).toBe(y.commonId);expect((await bindMail(a,sa.id,proof(123))).commonId).toBe(x.commonId);
 await expect(bindMail(b,sa.id,proof(123))).rejects.toThrow('SOURCE_NOT_FOUND');
 await expect(bindMail(a,sa.id,{...proof(123),evidence:{...evidence,subject:'Changed'}})).rejects.toThrow('COMMON_MAIL_IDENTITY_CHANGED');
 expect((await bindMail(a,sa.id,{...proof(124),evidence:{...evidence,messageId:null}})).matched).toBe(false);
 const otherTeam=randomUUID();await pool.query('INSERT INTO team VALUES($1,$2)',[otherTeam,'Other']);
 const d=new Directory(otherTeam),u=await d.login({issuer:'https://test/',subject:'c',email:'c@example.test'}),s=await d.registerSource(u,{instanceId:randomUUID(),displayName:'C'});
 expect((await bindMail(u,s.id,proof(123))).commonId).not.toBe(x.commonId);
});
test('two mailboxes admit only one analysis, share explicitly, revoke immediately',async()=>{
 const {Runs}=await import('../apps/history-api/src/runs.js');const runs=new Runs();
 const {SharedReports}=await import('../apps/history-api/src/shared-reports.js');const reports=new SharedReports();
 const ra=await directory.registerRunner(a,{requestId:randomUUID(),displayName:'A',agents:['codex'],sourceIds:[sa.id]});
 const rb=await directory.registerRunner(b,{requestId:randomUUID(),displayName:'B',agents:['codex'],sourceIds:[sb.id]});
 const input=(sourceId:string,mailId:number,runnerId:string)=>({sourceId,mailId,runnerId,messageId:evidence.messageId,subject:evidence.subject,mailEvidence:evidence,requestId:randomUUID(),agent:'codex' as const,executorKind:'local' as const,verifiedAt:new Date().toISOString()});
 const ia=input(sa.id,123,ra.id),ib=input(sb.id,789,rb.id);
 const results=await Promise.allSettled([runs.start(a,ia),runs.start(b,ib)]);
 expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);
 expect(results.filter(r=>r.status==='rejected').map(r=>String(r.reason))).toEqual(['Error: COMMON_MAIL_BUSY']);
 const first=results[0].status==='fulfilled',owner=first?a:b,reader=first?b:a,runner=first?ra:rb,req=first?ia:ib;
 const job=(results.find(r=>r.status==='fulfilled') as PromiseFulfilledResult<any>).value;
 expect((await runs.start(owner,req)).id).toBe(job.id);
 const claim=(await runs.claim(owner,runner.id,randomUUID(),runner.credential))!;
 await runs.complete(owner,job.id,{runnerId:runner.id,leaseToken:claim.leaseToken,generation:claim.generation,requestId:randomUUID(),result:{outcome:'completed',project:'unknown',report:'Shared synthetic report',question:'',knowledge:'',evidence:[]}},runner.credential);
 await expect(reports.get(reader,job.id)).rejects.toThrow('REPORT_NOT_FOUND');
 await reports.share(owner,job.id,{permission:'read'});
 const read=await reports.get(reader,job.id);expect(read.report).toBe('Shared synthetic report');expect(read.canEdit).toBe(false);
 expect(read).not.toHaveProperty('source_id');expect(read).not.toHaveProperty('relatedMails');
 expect(await reports.list(reader,first?sb.id:sa.id,first?789:123)).toHaveLength(1);
 await expect(reports.share(reader,job.id,{permission:'write'})).rejects.toThrow('OWNER_REQUIRED');
 await reports.share(owner,job.id,{permission:'none'});
 await expect(reports.get(reader,job.id)).rejects.toThrow('REPORT_NOT_FOUND');
 expect(await reports.list(reader,first?sb.id:sa.id,first?789:123)).toHaveLength(0);
 const {SharedHistory}=await import('../apps/history-api/src/shared-history.js');const history=new SharedHistory();
 await directory.grant(owner,first?sa.id:sb.id,{userId:reader.userId,permission:'write'});
 await history.handling(owner,job.id,true);
 expect((await history.get(owner,job.id)).handledAt).toBeTruthy();
 expect((await history.get(reader,job.id)).handledAt).toBeNull();
 await directory.grant(owner,first?sa.id:sb.id,{userId:reader.userId,permission:'none'});
});
test('revision CAS, exact retries, immutable history and conversation ACL',async()=>{
 const {SharedReports}=await import('../apps/history-api/src/shared-reports.js');const reports=new SharedReports();
 const {ReportCollaboration}=await import('../apps/history-api/src/report-collaboration.js');const collaboration=new ReportCollaboration();
 const row=(await pool.query('SELECT r.run_id AS id,s.owner_user_id FROM report_version r JOIN analysis_run a ON a.id=r.run_id JOIN mail_identity m ON m.id=a.mail_key JOIN source s ON s.store_id=m.store_id')).rows[0];
 const owner=row.owner_user_id===a.userId?a:b,other=owner===a?b:a,id=row.id;
 await reports.share(owner,id,{permission:'write'});
 const input=(report:string)=>({requestId:randomUUID(),expectedVersion:1,report,changeNote:'Synthetic correction',evidence:'Synthetic evidence'}),one=input('Version A'),two=input('Version B');
 const attempts=await Promise.allSettled([collaboration.save(owner,id,one),collaboration.save(other,id,two)]);
 expect(attempts.filter(x=>x.status==='fulfilled')).toHaveLength(1);
 expect(attempts.filter(x=>x.status==='rejected').map(x=>String(x.reason))).toEqual(['Error: REPORT_VERSION_CONFLICT']);
 const won=attempts[0].status==='fulfilled',actor=won?owner:other,request=won?one:two;
 expect(await collaboration.save(actor,id,request)).toEqual({version:2});
 await expect(collaboration.save(actor,id,{...request,report:'Changed retry'})).rejects.toThrow('REQUEST_CONFLICT');
 expect((await collaboration.revision(owner,id,1)).report).toBe('Shared synthetic report');
 expect((await collaboration.get(other,id)).version).toBe(2);
 await expect(pool.query('UPDATE report_revision SET report=$1 WHERE run_id=$2',['overwrite',id])).rejects.toThrow('IMMUTABLE_COLLABORATION_RECORD');
 const message={requestId:randomUUID(),kind:'decision',body:'Synthetic decision',evidence:'Proof'};
 const saved=await collaboration.message(other,id,message);expect(await collaboration.message(other,id,message)).toEqual(saved);
 expect((await collaboration.get(owner,id)).messages).toHaveLength(1);
 expect((await collaboration.get(owner,id)).version).toBe(2);
 await reports.share(owner,id,{permission:'read'});
 await expect(collaboration.save(other,id,{...input('Denied'),expectedVersion:2})).rejects.toThrow('REPORT_NOT_FOUND');
 await reports.share(owner,id,{permission:'none'});
 await expect(collaboration.revision(other,id,1)).rejects.toThrow('REPORT_NOT_FOUND');
 await expect(collaboration.get(other,id)).rejects.toThrow('REPORT_NOT_FOUND');
});
test('AI questions freeze report version, enforce runner limits and preserve report until explicit save',async()=>{
 const {ReportQuestions}=await import('../apps/history-api/src/report-questions.js');const questions=new ReportQuestions();
 const {ReportCollaboration}=await import('../apps/history-api/src/report-collaboration.js');const collaboration=new ReportCollaboration();
 const row=(await pool.query('SELECT r.run_id AS id,s.owner_user_id,s.id AS source_id FROM report_version r JOIN analysis_run a ON a.id=r.run_id JOIN mail_identity m ON m.id=a.mail_key JOIN source s ON s.store_id=m.store_id')).rows[0];
 const owner=row.owner_user_id===a.userId?a:b;
 const runner=await directory.registerRunner(owner,{requestId:randomUUID(),displayName:'Report reader',agents:['codex'],sourceIds:[row.source_id]});
 const input={requestId:randomUUID(),runnerId:runner.id,agent:'codex',expectedVersion:2,question:'Explain this report',allowEvidence:false};
 const job=await questions.start(owner,row.id,input,runner.credential);expect(job.execute).toBe(true);expect(job.context.version).toBe(2);
 expect((await questions.start(owner,row.id,input,runner.credential)).execute).toBe(false);
 await expect(questions.start(owner,row.id,{...input,requestId:randomUUID()},runner.credential)).rejects.toThrow('REPORT_AGENT_BUSY');
 const result={outcome:'completed',project:'unknown',report:'Synthetic AI answer',question:'',knowledge:'',evidence:[]};
 await questions.complete(owner,job.id,{result},runner.credential);await questions.complete(owner,job.id,{result},runner.credential);
 const after=await collaboration.get(owner,row.id);expect(after.version).toBe(2);expect(after.messages.filter(m=>m.kind==='answer')).toHaveLength(1);
 await expect(questions.complete(owner,job.id,{result:{...result,report:'Changed'}},runner.credential)).rejects.toThrow('RESULT_CONFLICT');
});
