import {readFile} from 'node:fs/promises';
import {randomBytes} from 'node:crypto';
import {join} from 'node:path';
import {HistoryClient} from '../../../packages/history-client/src/index.js';
import {ProtectedStore} from './protected-store.js';
import {createBrowserApp} from './browser-app.js';
import {NativeLogin} from './pkce.js';
import {LocalSession} from './session.js';
import {LocalProfile} from './profile.js';
import {localUiRoutes} from './ui-routes.js';
import {LocalRuntime} from './runtime.js';
import {fileURLToPath} from 'node:url';
import {z} from 'zod';
import {acquireInstance} from '../../../packages/runner/src/instance.js';
const root=process.env.TRIAGE_LOCAL_HOME;if(!root)throw new Error('TRIAGE_LOCAL_HOME required');
const settings=z.object({historyUrl:z.string().url(),auth:z.object({issuer:z.string().url(),clientId:z.string().min(1),audience:z.string().min(1)}),mailMcpUrl:z.string().url().optional()}).parse(JSON.parse(await readFile(join(root,'config','settings.json'),'utf8')));
const secrets=new ProtectedStore(join(root,'secrets'));
const login=new NativeLogin(settings.auth.issuer,settings.auth.clientId,settings.auth.audience);
const session=new LocalSession(login,secrets,async token=>(await new HistoryClient(settings.historyUrl,async()=>token).request('/me'))!);
const history=new HistoryClient(settings.historyUrl,()=>session.token());
const profile=new LocalProfile(history,session,secrets,settings.mailMcpUrl);
const runtime=new LocalRuntime(history,profile,session,secrets,new ProtectedStore(join(root,'work')));
const release=await acquireInstance(join(root,'app.lock'));
const port=3080;
const controlToken=randomBytes(32).toString('base64url');await secrets.write('cli-control',{port,token:controlToken});
const server=createBrowserApp(session,{port,controlToken,beforeLogout:()=>runtime.stop(),features:app=>{
  localUiRoutes(app,history,{selection:()=>profile.selection(),registerSource:b=>profile.registerSource(b),registerRunner:b=>profile.registerRunner(b),configure:async b=>{await runtime.stop();return profile.configure(b);},status:async()=>({...await profile.status() as object,runtime:runtime.status()})});
  app.get('/api/runtime',async(_req,res)=>res.json(runtime.status()));
  app.post('/api/runtime/start',async(req,res)=>res.json(await runtime.start(z.object({kind:z.enum(['analysis','sync'])}).strict().parse(req.body).kind)));
  app.post('/api/runtime/stop',async(_req,res)=>res.json(await runtime.stop()));
  app.get('/api/runtime/recovery',async(_req,res)=>res.json(await runtime.recovery()));
  app.post('/api/runtime/recovery',async(req,res)=>res.json(await runtime.resolve(z.object({action:z.enum(['archive-analysis','archive-sync','deliver','deliver-sync','recover'])}).strict().parse(req.body).action)));
},staticRoot:fileURLToPath(new URL('../../../../public/',import.meta.url))}).listen(port,'127.0.0.1');
server.on('error',()=>{void release().finally(()=>{process.exitCode=1;});});
for(const signal of ['SIGINT','SIGTERM'])process.once(signal,()=>{void runtime.stop().finally(()=>server.close(()=>{void release();}));});
