module.exports = {
  guide: [
    'README',
    {
      type: 'category',
      label: '현재 제품',
      collapsed: false,
      items: [
        'current-status',
        'architecture',
        'internals',
        'workflows',
        'specification',
        'security',
      ],
    },
    {
      type: 'category',
      label: '개발 안내',
      items: [{ type: 'autogenerated', dirName: 'guides' }],
    },
    {
      type: 'category',
      label: '설치·운영',
      items: [{ type: 'autogenerated', dirName: 'operations' }],
    },
    {
      type: 'category',
      label: 'API·데이터',
      items: [{ type: 'autogenerated', dirName: 'reference' }],
    },
    'implementation-plan',
    {
      type: 'category',
      label: '검증 기록',
      items: ['validation', { type: 'autogenerated', dirName: 'validation' }],
    },
    {
      type: 'category',
      label: '보존 문서',
      items: [{ type: 'autogenerated', dirName: 'archive' }],
    },
  ],
};
